//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueNha
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int IDKH { get; set; }
        public string SDT { get; set; }
        public string Hoten { get; set; }
        public string DiaChi { get; set; }
    }
}
