//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueNha
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTro
    {
        public int IDNha { get; set; }
        public string Tenduong { get; set; }
        public string DT { get; set; }
        public string TenChuNha { get; set; }
        public string SDT { get; set; }
        public string CTNha { get; set; }
        public string GioiThieu { get; set; }
        public string Gia { get; set; }
        public byte[] Hinh { get; set; }
        public string IDQuan { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
    }
}
